version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "webapp"
          ContainerPort: 80
          image: 039973338291.dkr.ecr.us-east-1.amazonaws.com/devops-workshop-app:latest
